### ISSUE TITLE
Carrots textures

### ISSUE THREAD

**Issue by NyankoSensei** [PilzAdam/farming_plus#6]
I have modified a bit textures for carrots for match a bit better minetest defaults colors see if you like it

![farming_carrot](https://f.cloud.github.com/assets/5476493/2263853/d9b84724-9e6a-11e3-93e8-5aa64774ed1b.png)
![farming_carrot_1](https://f.cloud.github.com/assets/5476493/2263854/d9c0b6d4-9e6a-11e3-90e6-216efd75f8cf.png)
![farming_carrot_3](https://f.cloud.github.com/assets/5476493/2263855/d9ca3ba0-9e6a-11e3-8ff8-2e43c30d20ca.png)
![farming_carrot_4](https://f.cloud.github.com/assets/5476493/2263856/d9fbb522-9e6a-11e3-9dcf-c31ae2ea3bbb.png)
![farming_carrot_2](https://f.cloud.github.com/assets/5476493/2263857/da2480ec-9e6a-11e3-90d2-c8593e687782.png)

Edit

Added potato

![farming_potato](https://f.cloud.github.com/assets/5476493/2263912/56e2ff3c-9e6b-11e3-902e-80e014f7965b.png)
![farming_potato_1](https://f.cloud.github.com/assets/5476493/2263913/56e7e060-9e6b-11e3-9bba-11e32ccf4e1b.png)
![farming_potato_2](https://f.cloud.github.com/assets/5476493/2263914/56ec1e82-9e6b-11e3-9d86-1d48a68221b9.png)
![farming_potato_3](https://f.cloud.github.com/assets/5476493/2263915/5701a6d0-9e6b-11e3-875c-235f9c2dd631.png)

and orange

![farming_orange](https://f.cloud.github.com/assets/5476493/2263898/3e55fc1c-9e6b-11e3-87ac-e9902fa88a71.png)
![farming_orange_1](https://f.cloud.github.com/assets/5476493/2263899/3e5b32e0-9e6b-11e3-8ef7-1e5f7b8e9e56.png)
![farming_orange_2](https://f.cloud.github.com/assets/5476493/2263900/3eba7d4a-9e6b-11e3-8c72-a79257163b6a.png)
![farming_orange_4](https://f.cloud.github.com/assets/5476493/2263901/3ed6045c-9e6b-11e3-936d-05d5a5a113a6.png)
![farming_orange_3](https://f.cloud.github.com/assets/5476493/2263902/3edafc0a-9e6b-11e3-9423-9870e8ef809c.png)

**Comment by VanessaE** [comment]
Merged with commits bcc4da2ffd38bba72a89db3b7cb7c9aa5f9c597e , d31ee3b8385a5425397823f8b469d16cf524d82f , and fa1e9b0454cd0e5dce91eafadc540df17cbdc356 .
