### ISSUE TITLE
what about other swords?

### ISSUE THREAD

**Issue by asl97** [PilzAdam/farming_plus#9]
there are diamonds, mese, bronze sword in default as well as cement, evil in gloopblock
and silver, mithril sword from moreores,  there might even be others, why not just do a simple string check like `string.match(tool, "sword")` instead?
that would cover every single possible sword.
https://github.com/PilzAdam/farming_plus/blob/master/pumpkin.lua#L68

**Comment by SmallJoker** [comment]
Why do it so complicated? Just check if the tool is enough sharp, means: fleshy > 4

**Comment by asl97** [comment]
how is it complicated?  wouldn't other tool also be sharp?

**Comment by SmallJoker** [comment]
That I mean. In the real life it would get hard to cut a pumpkin with a wooden tool.
This way, you also could use pickaxes, (wrench?) and axes.

**Comment by VanessaE** [comment]
One wouldn't carve a pumpkin with an axe though.  I think it's sufficient to use only a sword (as long as it is sharp enough), since it's the closest thing we have to a knife.
